version: '3.8'

services:
  web:
    build: .
    command: sh entrypoint.sh
    volumes:
      - .:/e_academy_backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    container_name: backend
    depends_on:
      - redis
      - celery_worker

  celery_worker:
    build: .
    command: celery -A e_academy worker --loglevel=info
    volumes:
      - .:/e_academy_backend
    env_file:
      - ./.env
    container_name: celery_worker
    depends_on:
      - redis

  redis:
    image: redis:6.0-alpine
    container_name: redis
    ports:
      - "6378:6379"
